### ISSUE TITLE
Freelancer.com

### ISSUE THREAD

**Issue by uzairnadeem201** [brodylarsen50/SocialFi#1]
I saw your job post on freelancer and i am willing to work on your project full time i have to  2 years of experience and i worked on 2 major project as React.js developer known as Audiosocket which is spotify competitor and aurahealth so feel free to contact me and discuss the work at hand in detail

**Comment by KingDeveloper1** [comment]
I saw your job on freelancer.
And I have a rich experience in this field.
I will work full time for your project
Thank you.
